services:
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./src/
    env_file:
      - .env
    environment:
      GIN_MODE: debug # release
      GOMAXPROCS: 1
      JWT_SECRET_KEY: jw_secret_key
      # RESEND_API_KEY: mock
      # NO_REPLY_EMAIL: no-reply@example.com
      API_HOST_URL: http://localhost:8080/
      APP_HOST_URL: http://localhost:8080/
      PROJECT_NAME: roady-app
      POSTGRES_OPEN_CONNS: 0
      POSTGRES_IDLE_CONNS: 2
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_ENDPOINT: http://minio:9000/
      S3_SECURE: "false"
      S3_BUCKET: goliath

      S3_REGION: us-east-1 # default region for minio
      STRIPE_API_KEY: api-key
      MONGO_URI: mongodb://mongo:27017

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    attach: false

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
    attach: false

volumes:
  postgres_data:
  mongo_data:
  minio_data:
